services:
  - type: web
    name: syro-telegram-bot
    env: python
    region: oregon
    plan: free
    branch: siddhant_dev
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    runtime: python-3.11
    envVars:
      - key: PORT
        value: 8000
      - key: TELEGRAM_TOKEN
        fromDatabase: true       # Pull from Render environment variables
      - key: GEMINI_API_KEY
        fromDatabase: true
      - key: MONGODB_URL
        fromDatabase: true
      - key: GOOGLE_PLACES_API_KEY
        fromDatabase: true
      - key: HUGGINGFACE_TOKEN
        fromDatabase: true
      - key: SPOTIFY_CLIENT_ID
        fromDatabase: true
      - key: SPOTIFY_CLIENT_SECRET
        fromDatabase: true
      - key: UPSTASH_REDIS_REST_URL
        fromDatabase: true
      - key: UPSTASH_REDIS_REST_TOKEN
        fromDatabase: true
    healthCheckPath: /health
